version: '3.8'

services:
  
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_mcp_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Apache Kafka
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka_server
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # Zookeeper (Required for Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  # Prometheus (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # ELK Stack (Elasticsearch, Logstash, Kibana)
  elk:
    image: sebp/elk:latest
    container_name: elk_stack
    restart: always
    ports:
      - "5601:5601"  # Kibana
      - "9200:9200"  # Elasticsearch
      - "5044:5044"  # Logstash

volumes:
  mysql_data:
